### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by TheLiao233** [lyuPang/AttnDreamBooth#1]
Hello, would you like to ask if it is normal for me to display insufficient CUDA memory when I use two a6000 graphics cards with 48G each memory in the third step of training?  Could you please tell me about your graphics memory usage during training?

In addition, when I used the default Settings in step1, the two graphics cards took up more than 20GB of memory, and step2 took up more than 80GB of memory.

Thanks

**Comment by lyuPang** [comment]
Happy to help! 

We usually trained our model on one A800 graphics card with 80G memory, and the third stage took up about 76G of memory. 

When using `n` graphics card, the total batch size calculation formula is `batch_size * gradient_accumulation * n`. If you encountered the issue of "CUDA out of memory", you could divide `batch_size` by `n`, or  decrease `batch_size` and increase `gradient_accumulation`, or use the setting of the fast version, which decreases `batch_size` and increase `learning_rate`.
